### ISSUE TITLE
logger.setLevel is not a function

### ISSUE THREAD

**Issue by slim-hmidi** [lilia-simeonova/jaccard-index#6]
I'm trying the code that you provide on readme and I got this error when I run the code:
```
/home/user/jaccard/node_modules/natural/lib/natural/brill_pos_tagger/lib/Brill_POS_Tagger.js:26
logger.setLevel('WARN');
       ^

TypeError: logger.setLevel is not a function
    at Object.<anonymous> (/home/user/jaccard/node_modules/natural/lib/natural/brill_pos_tagger/lib/Brill_POS_Tagger.js:26:8)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/user/jaccard/node_modules/natural/lib/natural/index.js:81:26)
    at Module._compile (module.js:573:30)

```
How can I fix that?

**Comment by AlexandruSimandi** [comment]
I know it's late and it looks like the creator won't help you, update the natural js dependency from 0.4.0 to 0.6.1

**Comment by slim-hmidi** [comment]
Thanks a lot
